repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    -   id: end-of-file-fixer
        exclude_types: [tex, text]
    -   id: trailing-whitespace
        exclude_types: [tex, text]
        exclude: mkdocs.yaml
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black