site_name: pylingdocs
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - mkdocs-click
  - markdown_include.include:
      base_path: docs
nav:
  - installation.md
  - usage.md
  - markdown_format.md
  - config.md
  - data_formats.md
  - extending.md
  - examples.md
  - output_formats.md
  - topic_index.md
theme:
  name: material
  icon:
    logo: octicons/book-24
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - toc.integrate
watch:
  - .