site_name: pylingdocs
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - mkdocs-click
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - installation.md
  - usage.md
  - markdown_format.md
  - config.md
  - data_formats.md
  - extending.md
  - examples.md
  - output_formats.md
  - topic_index.md
extra_css:
  - assets/nord.css
theme:
  name: material
  icon:
    logo: octicons/book-24
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - toc.integrate
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
watch:
  - .