name: lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  lint:
    name: Linting build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools<58
          python3 -m pip install .[clld,dev]
      - name: Check style against standards using prospector
        run: |
          prospector src/ --ignore-paths=src/pylingdocs/data/format_templates/
          prospector tests/
      - name: Check import order
        run: isort --check-only src/pylingdocs --diff
